version: '3'

services:
  gateway:
    build:
      context: ./newgo/gateway
      dockerfile: Dockerfile
    container_name: ${GATEWAY_CONTAINER_NAME}
    hostname: ${GATEWAY_CONTAINER_NAME}
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    env_file:
      - ./.env
    networks:
      expensify-network:
        aliases:
          - ${GATEWAY_CONTAINER_NAME}
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "expensify:host-gateway"
    depends_on:
      - server
      - auth

  server:
    build:
      context: ./newgo/server
      dockerfile: Dockerfile
    container_name: ${API_CONTAINER_NAME}
    hostname: ${API_CONTAINER_NAME}
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - ./.env
    networks:
      expensify-network:
        aliases:
          - ${API_CONTAINER_NAME}

  auth:
    build:
      context: ./newgo/auth
      dockerfile: Dockerfile
    container_name: ${AUTH_CONTAINER_NAME}
    hostname: ${AUTH_CONTAINER_NAME}
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    env_file:
      - ./.env
    networks:
      expensify-network:
        aliases:
          - ${AUTH_CONTAINER_NAME}

networks:
  expensify-network:
    driver: bridge